## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'dce', 'point-to-point', 'wifi' ], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point', 'wifi' ],
				  target='bin/gpsd_simulator',
				  source=['gpsd_simulator.cc'],
				  cflags=['-g', '-O0'],
				  )
